### ISSUE TITLE
Demo运行不了 提示如下问题！

### ISSUE THREAD

**Issue by i-haiyang** [bither/bither-android-lib#11]
![image](https://cloud.githubusercontent.com/assets/5258055/10933054/a14fc7b8-8310-11e5-9ff5-cb9359ad5697.png)

**Comment by jjz** [comment]
你可以使用编译的so试试

**Comment by i-haiyang** [comment]
请问 libbitherjni.so libjpegbither.so 是已经编译好的so 吗？  可以直接进行demo演示对吧

**Comment by i-haiyang** [comment]
帅哥， 我打印了一下压缩效率 把一个图片都压缩到20  用的时间 true的时间是最高的

**Comment by jjz** [comment]
@i-haiyang 压缩的效果很图片本身和压缩率也有一定的关系，true的时候有优化，所以时间会高，建议你使用那种原图，颜色比较简单的，容易比较，各种压缩率都可以使用 90，85了
