### ISSUE TITLE
32-bit instead of 64-bit

### ISSUE THREAD

**Issue by smallgirl** [bither/bither-android-lib#12]
libjpegbither.so is 32-bit instead of 64-bit , Don't it support 64 - bit ?

**Comment by dayday0769** [comment]
The same question

**Comment by dayday0769** [comment]
libjpeg-turbo does not support 64 bit

**Comment by cncomer** [comment]
这个不能支持armeabi-v8a么,现在越来越多的手机都是64位的了，自己编译源码可以在64位使用吗？

**Comment by zxkevin1989** [comment]
The same question

**Comment by zxkevin1989** [comment]
能支持 64位吗

**Comment by bithernet** [comment]
暂无支持 64 位的计划
