### ISSUE TITLE
couldn't find "libjpegbither.so"

### ISSUE THREAD

**Issue by DizzyDuan** [bither/bither-android-lib#14]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.testjpg-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.testjpg-1/lib/arm64, /data/app/com.example.testjpg-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libjpegbither.so"

**Comment by jolly336** [comment]
Do you use android_studio tools? If so,you should create a directory named "jniLibs" in main and put so files in this dir,otherwise you should edit build.gradle file and the libs DSL statement.Like this:
```
android {
  ...
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
}
```

**Comment by DizzyDuan** [comment]
@haoxunwang The problem has been going for a long time, the reason is not what you said. This library does not support 64-bit.
