### ISSUE TITLE
The result I got is not as you say "save 5-10 times of image space"?

### ISSUE THREAD

**Issue by WhoIsAlfred** [bither/bither-android-lib#5]
I download your project and test the NativeUtil.compressBitmap method. the result is not as good as you say.

I use 4 pictures. here is the result:

picture | optimize_coding = false | optimize_coding = true | jpeg compress ratio
------------ | ------------- | ------------- | -------------
picture 1 | 46KB | 44KB | 50
picture 2 | 62KB | 59KB | 50
picture 3 | 215KB | 194KB | 100
picture 4 | 369KB | 348KB | 100

Obviously, the size which set optimize_coding to false are only 1.05 - 1.10 times of the others, not as you say  "save 5-10 times of image space". And the image quality is almost same. 

Is there something wrong? Expect your reply！

Thanks.

**Comment by jjz** [comment]
Different source images can result in different test results. In some cases it may be subtle.

In our test code, we always use `libjpeg-turbo` to compress the bitmap, either when the optimize_coding is true or false.  `libjpeg-turbo` itself is already better than the Android built in compression.

**Comment by WhoIsAlfred** [comment]
Thank you for reply!

Actually, I had compared the picture size of using libjpeg-turbo with using the original android lib, the result is that libjpeg-turbo is really smaller, but only about 5 percent.

Take above into consider, the size is only 10% ~ 15% percent smaller than android original lib. I approve of that libjpeg-turbo will enhance the performance and reduce image size, but '5-10 times' is incredible.

Honestly, ‘10 times’ is enough to induce a revolution of science. I believe that Google will make mistakes, but I don't think she will miss a technical revolution.

If it is not a secret, could you please upload the pictures that you tested. Thank you!

wish your reply!

**Comment by songchenwen** [comment]
`Image quality` we said is not only the compression rate of an image, but also how we look and feel the image. When the `image quality`s are felt the same, libjpeg-turbo with `optimize_coding` will save you 5 ~ 10 times space.  

We admit that this can be very subjective. Sorry for the misleading.
