### ISSUE TITLE
Could not build with x86

### ISSUE THREAD

**Issue by pip1998** [bither/bither-android-lib#6]
Hope supported

**Comment by songchenwen** [comment]
Sorry.

This is only a lib to optimize the JPEG compression process on Android. There's little reason to make effort to support x86 platform.

Maybe you can find some information you need [here](http://www.libjpeg-turbo.org)

PR welcome.

**Comment by ray007great** [comment]
现在android手机很多cpu的，有x86的貌似

**Comment by dayday0769** [comment]
64位的也不行

**Comment by androidmalin** [comment]
@songchenwen 你说的是，暂时不支持x86 吗？

**Comment by jjz** [comment]
@dayday0769  还没有在64位上面编译

**Comment by androidmalin** [comment]
@jjz 怎么样编译，才能够支持64位，支持arm-v7和x86呢？

**Comment by zhiqiangli520210** [comment]
i want to know how can i make x86？

**Comment by bithernet** [comment]
Currently we do not support x86 on this lib.
