### ISSUE TITLE
使用哪个so文件的问题

### ISSUE THREAD

**Issue by ray007great** [bither/bither-android-lib#8]
在readme里下面
System.loadLibrary("jpegpi");
System.loadLibrary("pijni");
在demo里
System.loadLibrary("jpegbither");
System.loadLibrary("bitherjni");

二者好像不是很一样。

直接将jpegbither和bitherjni的so文件复制进目录里，native util的compressBitmap会找不到相应的jni函数。

开发工具是android studio

**Comment by zhangtengchao** [comment]
你现在可以用了么？

**Comment by ray007great** [comment]
没有解决就没在用了，等熟悉ndk了再来看下吧。。。我感觉文档不是很完整。

**Comment by jjz** [comment]
https://github.com/bither/bither-android-lib/tree/master/libjpeg-turbo-android/use-libjpeg-turbo-android 这里面的代码可以直接在android studio里面运行

**Comment by zhangtengchao** [comment]
但是里面只有armeabi的库，如何编出其他的库？

**Comment by jjz** [comment]
你想要什么样的库呢？

**Comment by zhangtengchao** [comment]
https://github.com/bither/bither-android-lib/issues/6

**Comment by CodingHornet** [comment]
@jjz 你已经在Android Studio中跑起来了么，能给我一个运行Demo么，我导入之后bitherlibjni.c报错，求指导

**Comment by jjz** [comment]
https://github.com/bither/bither-android-lib/tree/master/libjpeg-turbo-android/use-libjpeg-turbo-android 这个就是Demo。

**Comment by CodingHornet** [comment]
@jjz 这个我在eclipse里用可以，但是在AS里就会报很多乱七八糟的错，还有C++的错........，你是在AS里用的么

**Comment by jjz** [comment]
@CodingHornet eclipse

**Comment by LinSJ92** [comment]
@jjz Android Studio 提示找不到native方法,有解决办法么

**Comment by jjz** [comment]
@CodingHornet 包名必须和demo的一样

**Comment by dayday0769** [comment]
不能在64位系统运行。。。
