### ISSUE TITLE
how to use this lib

### ISSUE THREAD

**Issue by fostion** [bither/bither-android-lib#9]
readme:
System.loadLibrary("jpegpi");
System.loadLibrary("pijni");
demo:
System.loadLibrary("jpegbither");
System.loadLibrary("bitherjni");

it is difference.
and when i you it , there are some some wrong  "Native method not found"
anyone know how to do it

**Comment by Aeolus-dan** [comment]
me， too .  I also want to know how to do it .Do you know now ?

**Comment by chenhaijai** [comment]
EDI

**Comment by bithernet** [comment]
Currently we do not provide supporting service for this lib.
